### ISSUE TITLE
Reappearing error in log

### ISSUE THREAD

**Issue by 1951FDG** [Alberto96/android_kernel_ulefone_k11ta_a#1]
Hi,

I've been running your custom rom on my Ulefone Future, 13.0-20170531, but looking at the logs in Android Studio, I constantly get error:

`E/AudioParamParser: appHandleThreadLoop(), inotify_add_watch failed !!! try again...`

Don't know what is causing this, could it be a propietary driver malfunctioning? Can you help me troubleshoot?

**Comment by Alberto96** [comment]
Hi,

Exactly, a proprietary audio driver is causing this issue, but apparently there is no real-life impact, neither it is possible to not use the proprietary audio driver.

Cheers
